## Numpy
numpy is used for fast numerical computations , efficient array and matrix operations ,it uses less memory than using Python lists,and it have many built-in math functions

## to create arrays using numpy

In [2]:
import numpy as np

In [10]:
a=np.array([1,2,3,4,5])

## to make array of zeros only(1D)

In [11]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## to make array of ones only(1D)

In [13]:
one=np.ones(10)
print(one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## to make array of ones only(with diffirent shapes)
## to make array of zeros only(with diffirent shapes)

In [16]:
zz=np.zeros((2,3))
print(zz)
one2=np.ones((4,3))
print(one2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## creates 5 equally spaced values from 0 to 1

In [17]:
r=np.linspace(0,1,5)
print(r)

[0.   0.25 0.5  0.75 1.  ]


## to make arrays with random numbers (by using random.rand)

In [19]:
random=np.random.rand(3,10)
print(random)

[[0.86865139 0.14256789 0.95427689 0.22387827 0.48760331 0.09085737
  0.78027399 0.98053566 0.30335911 0.45506297]
 [0.00259785 0.66070955 0.95141518 0.5615878  0.05284958 0.46621609
  0.89590448 0.49997522 0.87171127 0.92980985]
 [0.91457392 0.09401376 0.21382099 0.8246091  0.32817314 0.0061148
  0.09790571 0.68326123 0.34222224 0.24529619]]


## Array Attributes, Indexing & Slicing
(By using this rule array[row,column])


In [27]:
m=np.array([[1,2,3],[5,6,7],[8,9,10]])
print(m.shape)

(3, 3)


In [28]:
print(m[1,2]) #row:1,col:3

7


In [29]:
print(m[:,2]) # all rows, col:2

[ 3  7 10]


In [31]:
print(m[2,:]) #row:1,all col

[ 8  9 10]


## Vectorized Operations
apply operations on arrays using numpy to make faster and more readable code than using loops 

In [ ]:
array3=np.array([1,10,15,30])
sum=(array3+array3) #sum element by element
print(sum)

[ 2 20 30 60]


In [ ]:
mult=(array3*array3) #multiply element by element
print(mult)

[  1 100 225 900]


In [ ]:
m=(array3.mean()) #find the mean
print(m)

14.0


In [38]:
mx=(array3.max()) #find the max element
print(mx)

30


In [39]:
mn=(array3.min()) #find the min element
print(mn)

1


In [ ]:
a=(array3[array3>3]) #boolean masking
print(a) 

[10 15 30]


## Broadcasting
Numpy automatically expands the smaller array ro match the larger one then doing the operations
for example adding a single number to every element,or adding a 1D array to 2D array


In [41]:
m=np.array([[1,2,3],[4,5,6]])
r=np.array([5,10,20])
print(m+r)

[[ 6 12 23]
 [ 9 15 26]]


In [43]:
print(m+5)
print(r+7)

[[ 6  7  8]
 [ 9 10 11]]
[12 17 27]


## Hands-On Lab

Step 1: Create a 2D array of shape (4, 4) filled with values 1-16 and print its shape and dtype.


In [52]:
arr=np.arange(1,17,1)
arr1=arr.reshape(4,4)
print(arr1)
print(arr1.shape)
print(arr1.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
int64


Step 2: Use slicing to extract the second column and the last row.


In [ ]:
print(arr1[:,1]) #the second colum

[ 2  6 10 14]


In [ ]:
print(arr1[-1]) #the last row

[13 14 15 16]


Step 3: Use a boolean mask to select all values greater than the array's mean.


In [ ]:
mean1=arr1.mean()
print("values greater than the mean")
print(arr1[arr1>mean1])

greater than mean
[ 9 10 11 12 13 14 15 16]


Step 4: Add a 1D row array to every row of a 2D array using broadcasting, and verify the result manually.

In [63]:
row=np.array([15,30,35,40])
res=arr1+row
print(res)
print("Manual verification")
print(arr1[0],"+",row,"=",arr1[0]+row)
print(arr1[1],"+",row,"=",arr1[1]+row)
print(arr1[2],"+",row,"=",arr1[2]+row)
print(arr1[3],"+",row,"=",arr1[3]+row)


[[16 32 38 44]
 [20 36 42 48]
 [24 40 46 52]
 [28 44 50 56]]
Manual verification
[1 2 3 4] + [15 30 35 40] = [16 32 38 44]
[5 6 7 8] + [15 30 35 40] = [20 36 42 48]
[ 9 10 11 12] + [15 30 35 40] = [24 40 46 52]
[13 14 15 16] + [15 30 35 40] = [28 44 50 56]
