## Linear Algebra for ML
Linear Algebra is a branch of math that covers vectors,matrices,and linear transformations.it forms the basis of how data can be analyzed and represented and is thus crucial in Machine Learning.

## Why Linear Algebra Matters
Linear Algebra forms the basis of Machine Learning.
- A vector is a single data point.
- A matrix is an entrie dataset.
- Machine Learning algorithms perform dot products to predict values.
- Multipilication of matrices enables predicition on many data points at once.

## Vectors
is a one dimentional array of numbers.
In Machine Learning, one vector crossponds one sample while values are features.

In [6]:
import numpy as np
student=np.array([15,95])
print(student)
print(student.shape)

[15 95]
(2,)


This vector contains:
- Age=15
- gpa=95
- shape=(2,)

## Matrices
A matrix is a group of vectors,row crossepond to samples and columns crossepond to features.

In [9]:
students=np.array([[25,100,50],[50,60,70],[100,200,400]])
print(students)
print(students.shape)

[[ 25 100  50]
 [ 50  60  70]
 [100 200 400]]
(3, 3)


3 rows means 3 samples
3 columns means 3 features
(3 students and 3 features)

## Dot Product
the dot product entails multiplying crossponding entries in two vectors and summing the products,to generates a single number,it used in Machine Learning to generate predicitions. 

In [10]:
features=np.array([1,2,3])
weights=np.array([4,5,6])
prediction=np.dot(features,weights)
print(prediction)

32


By hand
(1*4)+(2*5)+(3*6)
=(4)+(10)+(18)
=32

In [11]:
x=np.array([2,5])
y=np.array([3,6])
result=np.dot(x,y)
print(result)

36


## Matrix Multiplication
matrix multiplication involoves performing dot products on multiple instance simultaneously
## Rule
(mxn)x(nxp)
the inner dimensions should match.

In [12]:
w=np.array([[1,2,3],[4,5,6]])
z=np.array([2,3,1])
predict=w@z
print(predict)

[11 29]


By hand
=((1*2)+(2*3)+(3*1)),((4*2)+(5*3)+(6*1))
=(2+6+3),(8+15+6)
=(11,29)

## Compatibillity Rule for Matrices
in order to multiply matrices, the number of columns of the first matrix needs to match the number of rows of the second matrix otherwise the NumPy will throw a ValueError

## Hands-on-Lab
## Step 1: Represent three data samples as a (3 × features) NumPy matrix.

In [29]:
data=np.array([[25,5000,3],[30,40,1000],[33,6200,5]])
print(data)
print("shape",data.shape)

[[  25 5000    3]
 [  30   40 1000]
 [  33 6200    5]]
shape (3, 3)


we have three rows--> three samples
abd three columns--> three features
so the shape is (3,3)

## Step 2: Compute the dot product of one sample vector with a weight vector by hand, then verify it with np.dot.

In [24]:
sample=data[0]
w=np.array([0.1,0.0002,2])

By Hand
(25*0.1)=2.5
+
(5000*0.0002)=1
+
(3*2)=6
2.5+1+6=9.5

In [25]:
result2=np.dot(sample,w)
print(result2)

9.5


the np.dot function multiply crossponding elements then sum all results

## Step 3: Use matrix multiplication (@) to produce a prediction for all three samples at once.

In [27]:
predictions2=data @ w
print(predictions2)

[   9.5   2003.008   14.54 ]


np.dot()+np.dot()+np.dot()
(@) calculate all rows at once.

## Step 4: Deliberately create a shape-mismatch error, read the message, and explain in Markdown why it
occurred and how to fix it.

## Wrong Example

In [33]:

A=np.array([[1,2],[3,4]])
B=np.array([1,2,3])
print(A @ B)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

we have in this data sample a three rows--> three samples and three columns--> three features
so the shape will be (3,3)

## Why did the error happen?
A has shape(2,2)
B has a shape(3,)
the inner dimensions do not match.

## How to fix it?
reshape the matrices so that the number of columns in the first matrix equals the number
of rows in the second matrix.
change the B matrix to have the shape (2,n)


In [32]:
A=np.array([[1,2],[3,4]])
B=np.array([1,2])
print(A@B)

[ 5 11]
